/* file: msg.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\nituser\AppData\Local\Temp\Cfg_Gen-1707581391013-0\OsProxyFiles-1707581459714-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Sat Feb 10 17:11:02 2024 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <Os.h>


/* END OF C:\nit-au-03\AUTOSAR_Exercises\AFS\Appl\GenDataVtt\msg.c */

